env: "development"

database:
  host: localhost
  port: "5441"
  user: "postgres"
  dbname: "currency-wallet"
  max_attempts: 10

kafka:
  outbox:
    retries: 5
    topic:
      - "order"
      - "metrics"
    brokers:
      - "localhost:9092"

redis:
  host: "localhost"
  port: "6391"
  password: ""
  dbnumber: 0

domain: "localhost"

prometheus:
  host: "localhost"
  port: 5001
  timeout: 4s
  debug: true
  idle_timeout: 60s

http_server:
  host: 0.0.0.0
  port: 5000
  timeout: 4s
  debug: true
  idle_timeout: 60s

grpc_clients:
  grpc_exchanger:
    host: "localhost"
    port: "44044"
    timeout: 360s
    retries: 5




