env: "development"

database:
  host: db
  port: "5432"
  user: "postgres"
  dbname: "currency-wallet"
  max_attempts: 10

kafka:
  notification:
    retries: 5
    group_id: "notification"
    topic:
      - "notification"
    brokers:
      - "localhost:9092"

redis:
  host: "redis"
  port: "6379"
  password: ""
  dbnumber: 0

domain: "localhost"

prometheus:
  host: "localhost"
  port: 5001
  timeout: 4s
  debug: true
  idle_timeout: 60s

http_server:
  host: 0.0.0.0
  port: 5000
  timeout: 4s
  debug: true
  idle_timeout: 60s

grpc_clients:
  grpc_exchanger:
    host: "localhost"
    port: "44044"
    timeout: 360s
    retries: 5




