basePath: /api/v1
definitions:
  api.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  user.AuthResponse:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  user.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  user.LoginResponse:
    properties:
      email:
        type: string
      error:
        type: string
      status:
        type: string
      username:
        type: string
    type: object
  wallet.CurrencyWalletResponse:
    properties:
      rates:
        additionalProperties:
          type: number
        type: object
    type: object
  wallet.DepositOrWithdrawRequest:
    properties:
      amount:
        type: number
      currency:
        type: string
    required:
    - amount
    - currency
    type: object
  wallet.DepositOrWithdrawResponse:
    properties:
      balances:
        additionalProperties:
          type: number
        type: object
      error:
        type: string
      status:
        type: string
    type: object
  wallet.ExchangeRequest:
    properties:
      amount:
        type: number
      from_currency:
        type: string
      to_currency:
        type: string
    required:
    - amount
    - from_currency
    - to_currency
    type: object
host: localhost:5000
info:
  contact:
    name: GitHub
    url: https://github.com/Sanchir01
  description: This is a sample server seller
  termsOfService: http://swagger.io/terms/
  title: "\U0001F680 Currency Wallet"
  version: "1.0"
paths:
  /balance:
    get:
      consumes:
      - application/json
      description: balance user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wallet.CurrencyWalletResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      security:
      - refreshToken: []
      summary: GetBalanceHandler
      tags:
      - wallet
  /deposit:
    post:
      consumes:
      - application/json
      description: balance user
      parameters:
      - description: deposit body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/wallet.DepositOrWithdrawRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wallet.DepositOrWithdrawResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      security:
      - refreshToken: []
      summary: GetBalanceHandler
      tags:
      - wallet
  /exchange:
    post:
      consumes:
      - application/json
      description: balance user
      parameters:
      - description: deposit body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/wallet.ExchangeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wallet.DepositOrWithdrawResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      security:
      - refreshToken: []
      summary: GetBalanceHandler
      tags:
      - wallet
  /exchanger/rates:
    get:
      consumes:
      - application/json
      description: all currency wallet
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wallet.CurrencyWalletResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      security:
      - refreshToken: []
      summary: GetAllCurrencyHandler
      tags:
      - wallet
  /login:
    post:
      consumes:
      - application/json
      description: login user
      parameters:
      - description: auth body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Login
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: register user
      parameters:
      - description: login body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.LoginRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Auth
      tags:
      - auth
  /withdraw:
    post:
      consumes:
      - application/json
      description: balance user
      parameters:
      - description: withdraw body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/wallet.DepositOrWithdrawRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wallet.DepositOrWithdrawResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      security:
      - refreshToken: []
      summary: WithdrawWallet
      tags:
      - wallet
securityDefinitions:
  AccessTokenCookie:
    in: cookie
    name: accessToken
    type: apiKey
  RefreshTokenCookie:
    in: cookie
    name: refreshToken
    type: apiKey
swagger: "2.0"
